IF
  Global("RandomBeenSet38872272","%Undercity%",0)
THEN
  RESPONSE %spawnRem%
    SetGlobal("RandomBeenSet38872272","%Undercity%",1)
    SetGlobal("SpawnReset38872272","%Undercity%",1)
RESPONSE %spawnPerc%
    Continue()
END
//Spawnpoint % code above

IF
  RandomNum(1,1)
  Global("RandomSet38872272_2","%Undercity%",0)
  Global("RandomBeenSet38872272","%Undercity%",0)
THEN
  RESPONSE #100
    SetGlobal("RandomSet38872272_2","%Undercity%",1)
    SetGlobal("RandomBeenSet38872272","%Undercity%",1)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #90
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHOUL",[3887.2272],0)  // Ghoul
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #90
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHOUL",[3887.2272],0)  // Ghoul
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #90
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHOUL",[3887.2272],0)  // Ghoul
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #90
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHOUL",[3887.2272],0)  // Ghoul
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #90
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHOUL",[3887.2272],0)  // Ghoul
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #90
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHOUL",[3887.2272],0)  // Ghoul
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #80
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHOUL",[3887.2272],0)  // Ghoul
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #80
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHOUL",[3887.2272],0)  // Ghoul
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #80
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHOUL",[3887.2272],0)  // Ghoul
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHOUL",[3887.2272],0)  // Ghoul
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHOUL",[3887.2272],0)  // Ghoul
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHOUL",[3887.2272],0)  // Ghoul
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #25
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHOUL",[3887.2272],0)  // Ghoul
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #25
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHOUL",[3887.2272],0)  // Ghoul
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #25
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHOUL",[3887.2272],0)  // Ghoul
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #25
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHOUL",[3887.2272],0)  // Ghoul
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHOUL",[3887.2272],0)  // Ghoul
    CreateCreature("GHOUL",[3887.2272],0)  // Ghoul
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #25
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHOUL",[3887.2272],0)  // Ghoul
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHOUL",[3887.2272],0)  // Ghoul
    CreateCreature("GHOUL",[3887.2272],0)  // Ghoul
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #35
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHOUL",[3887.2272],0)  // Ghoul
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #35
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHOUL",[3887.2272],0)  // Ghoul
    CreateCreature("GHOUL",[3887.2272],0)  // Ghoul
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #60
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHAST",[3887.2272],0)  // Ghast
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #60
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHAST",[3887.2272],0)  // Ghast
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #60
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHAST",[3887.2272],0)  // Ghast
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHAST",[3887.2272],0)  // Ghast
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHAST",[3887.2272],0)  // Ghast
    CreateCreature("GHAST",[3887.2272],0)  // Ghast
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHAST",[3887.2272],0)  // Ghast
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHAST",[3887.2272],0)  // Ghast
    CreateCreature("GHAST",[3887.2272],0)  // Ghast
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHAST",[3887.2272],0)  // Ghast
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHAST",[3887.2272],0)  // Ghast
    CreateCreature("GHAST",[3887.2272],0)  // Ghast
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIM01",[3887.2272],0)  // Vampire Male
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIF01",[3887.2272],0)  // Vampire Female
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIM01",[3887.2272],0)  // Vampire Male
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIF01",[3887.2272],0)  // Vampire Female
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIM01",[3887.2272],0)  // Vampire Male
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIF01",[3887.2272],0)  // Vampire Female
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIM01",[3887.2272],0)  // Vampire Male
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIF01",[3887.2272],0)  // Vampire Female
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIM01",[3887.2272],0)  // Vampire Male
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIF01",[3887.2272],0)  // Vampire Female
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIM01",[3887.2272],0)  // Vampire Male
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIF01",[3887.2272],0)  // Vampire Female
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIM01",[3887.2272],0)  // Vampire Male
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIF01",[3887.2272],0)  // Vampire Female
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIM01",[3887.2272],0)  // Vampire Male
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIF01",[3887.2272],0)  // Vampire Female
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIM01",[3887.2272],0)  // Vampire Male
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIF01",[3887.2272],0)  // Vampire Female
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIM01",[3887.2272],0)  // Vampire Male
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIF01",[3887.2272],0)  // Vampire Female
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIM01",[3887.2272],0)  // Vampire Male
    CreateCreature("VAMPIF01",[3887.2272],0)  // Vampire Female
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIM01",[3887.2272],0)  // Vampire Male
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIF01",[3887.2272],0)  // Vampire Female
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIM01",[3887.2272],0)  // Vampire Male
    CreateCreature("VAMPIF01",[3887.2272],0)  // Vampire Female
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIM01",[3887.2272],0)  // Vampire Male
    CreateCreature("VAMPIF01",[3887.2272],0)  // Vampire Female
    CreateCreature("VAMPIF01",[3887.2272],0)  // Vampire Female
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIM01",[3887.2272],0)  // Vampire Male
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIF01",[3887.2272],0)  // Vampire Female
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #14
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIM01",[3887.2272],0)  // Vampire Male
    CreateCreature("VAMPIF01",[3887.2272],0)  // Vampire Female
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #6
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIM01",[3887.2272],0)  // Vampire Male
    CreateCreature("VAMPIF01",[3887.2272],0)  // Vampire Female
    CreateCreature("VAMPIF01",[3887.2272],0)  // Vampire Female
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END




IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #90
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHOUL",[3887.2272],0)  // Ghoul
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #90
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHOUL",[3887.2272],0)  // Ghoul
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #90
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHOUL",[3887.2272],0)  // Ghoul
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #90
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHOUL",[3887.2272],0)  // Ghoul
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #90
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHOUL",[3887.2272],0)  // Ghoul
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #90
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHOUL",[3887.2272],0)  // Ghoul
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #80
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHOUL",[3887.2272],0)  // Ghoul
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #80
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHOUL",[3887.2272],0)  // Ghoul
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #80
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHOUL",[3887.2272],0)  // Ghoul
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHOUL",[3887.2272],0)  // Ghoul
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHOUL",[3887.2272],0)  // Ghoul
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHOUL",[3887.2272],0)  // Ghoul
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #25
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHOUL",[3887.2272],0)  // Ghoul
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #25
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHOUL",[3887.2272],0)  // Ghoul
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #25
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHOUL",[3887.2272],0)  // Ghoul
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #25
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHOUL",[3887.2272],0)  // Ghoul
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHOUL",[3887.2272],0)  // Ghoul
    CreateCreature("GHOUL",[3887.2272],0)  // Ghoul
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #25
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHOUL",[3887.2272],0)  // Ghoul
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHOUL",[3887.2272],0)  // Ghoul
    CreateCreature("GHOUL",[3887.2272],0)  // Ghoul
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    CreateCreature("ZOMBIE",[3887.2272],0)  // Zombie
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #35
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHOUL",[3887.2272],0)  // Ghoul
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #35
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHOUL",[3887.2272],0)  // Ghoul
    CreateCreature("GHOUL",[3887.2272],0)  // Ghoul
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #60
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHAST",[3887.2272],0)  // Ghast
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #60
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHAST",[3887.2272],0)  // Ghast
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #60
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHAST",[3887.2272],0)  // Ghast
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHAST",[3887.2272],0)  // Ghast
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHAST",[3887.2272],0)  // Ghast
    CreateCreature("GHAST",[3887.2272],0)  // Ghast
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHAST",[3887.2272],0)  // Ghast
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHAST",[3887.2272],0)  // Ghast
    CreateCreature("GHAST",[3887.2272],0)  // Ghast
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHAST",[3887.2272],0)  // Ghast
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("GHAST",[3887.2272],0)  // Ghast
    CreateCreature("GHAST",[3887.2272],0)  // Ghast
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIM01",[3887.2272],0)  // Vampire Male
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIF01",[3887.2272],0)  // Vampire Female
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIM01",[3887.2272],0)  // Vampire Male
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIF01",[3887.2272],0)  // Vampire Female
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIM01",[3887.2272],0)  // Vampire Male
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIF01",[3887.2272],0)  // Vampire Female
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIM01",[3887.2272],0)  // Vampire Male
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIF01",[3887.2272],0)  // Vampire Female
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIM01",[3887.2272],0)  // Vampire Male
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIF01",[3887.2272],0)  // Vampire Female
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIM01",[3887.2272],0)  // Vampire Male
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIF01",[3887.2272],0)  // Vampire Female
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIM01",[3887.2272],0)  // Vampire Male
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIF01",[3887.2272],0)  // Vampire Female
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIM01",[3887.2272],0)  // Vampire Male
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIF01",[3887.2272],0)  // Vampire Female
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIM01",[3887.2272],0)  // Vampire Male
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIF01",[3887.2272],0)  // Vampire Female
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIM01",[3887.2272],0)  // Vampire Male
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIF01",[3887.2272],0)  // Vampire Female
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIM01",[3887.2272],0)  // Vampire Male
    CreateCreature("VAMPIF01",[3887.2272],0)  // Vampire Female
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIM01",[3887.2272],0)  // Vampire Male
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIF01",[3887.2272],0)  // Vampire Female
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIM01",[3887.2272],0)  // Vampire Male
    CreateCreature("VAMPIF01",[3887.2272],0)  // Vampire Female
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIM01",[3887.2272],0)  // Vampire Male
    CreateCreature("VAMPIF01",[3887.2272],0)  // Vampire Female
    CreateCreature("VAMPIF01",[3887.2272],0)  // Vampire Female
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset38872272","%Undercity%",0)
  Global("RandomSet38872272_2","%Undercity%",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("SHADOW01",[3887.2272],0)  // Shadow
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    CreateCreature("WRAITH01",[3887.2272],0)  // Wraith
    CreateCreature("NEVM1",[3887.2272],0)  // Wight
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIM01",[3887.2272],0)  // Vampire Male
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIF01",[3887.2272],0)  // Vampire Female
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #14
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIM01",[3887.2272],0)  // Vampire Male
    CreateCreature("VAMPIF01",[3887.2272],0)  // Vampire Female
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
  RESPONSE #6
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("VAMPIM01",[3887.2272],0)  // Vampire Male
    CreateCreature("VAMPIF01",[3887.2272],0)  // Vampire Female
    CreateCreature("VAMPIF01",[3887.2272],0)  // Vampire Female
    SetGlobalTimer("012338872272","%Undercity%",EIGHT_HOURS)
END



IF
  !Range([PC],35)
  Global("SpawnReset38872272","%Undercity%",1)
  GlobalTimerExpired("012338872272","%Undercity%")
THEN
  RESPONSE #100
    SetGlobal("SpawnReset38872272","%Undercity%",0)
    SetGlobal("RandomBeenSet38872272","%Undercity%",0)
    SetGlobal("RandomSet38872272_2","%Undercity%",0)
END

IF
  Range([PC],35)
  Global("SpawnReset38872272","%Undercity%",0)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset38872272","%Undercity%",1)
    CreateCreature("SKELET_A",[3887.2272],0)  // ~Skeleton~
    SetGlobalTimer("012338872272","%Undercity%",2400)
END

