IF
  RandomNum(1,1)
  Global("RandomSet24232007_3","AR7223",0)
  Global("RandomBeenSet24232007","AR7223",0)
THEN
  RESPONSE #100
    SetGlobal("RandomSet24232007_3","AR7223",1)
    SetGlobal("RandomBeenSet24232007","AR7223",1)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #90
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHOUL",[2423.2007],0)  // Ghoul
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #90
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHOUL",[2423.2007],0)  // Ghoul
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #90
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHOUL",[2423.2007],0)  // Ghoul
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #90
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHOUL",[2423.2007],0)  // Ghoul
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #90
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHOUL",[2423.2007],0)  // Ghoul
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #90
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHOUL",[2423.2007],0)  // Ghoul
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #80
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHOUL",[2423.2007],0)  // Ghoul
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #80
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHOUL",[2423.2007],0)  // Ghoul
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #80
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHOUL",[2423.2007],0)  // Ghoul
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHOUL",[2423.2007],0)  // Ghoul
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHOUL",[2423.2007],0)  // Ghoul
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHOUL",[2423.2007],0)  // Ghoul
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #25
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHOUL",[2423.2007],0)  // Ghoul
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #25
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHOUL",[2423.2007],0)  // Ghoul
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #25
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHOUL",[2423.2007],0)  // Ghoul
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #25
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHOUL",[2423.2007],0)  // Ghoul
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHOUL",[2423.2007],0)  // Ghoul
    CreateCreature("GHOUL",[2423.2007],0)  // Ghoul
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #25
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHOUL",[2423.2007],0)  // Ghoul
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHOUL",[2423.2007],0)  // Ghoul
    CreateCreature("GHOUL",[2423.2007],0)  // Ghoul
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #35
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHOUL",[2423.2007],0)  // Ghoul
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #35
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHOUL",[2423.2007],0)  // Ghoul
    CreateCreature("GHOUL",[2423.2007],0)  // Ghoul
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #60
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHAST",[2423.2007],0)  // Ghast
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #60
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHAST",[2423.2007],0)  // Ghast
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #60
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHAST",[2423.2007],0)  // Ghast
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHAST",[2423.2007],0)  // Ghast
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHAST",[2423.2007],0)  // Ghast
    CreateCreature("GHAST",[2423.2007],0)  // Ghast
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHAST",[2423.2007],0)  // Ghast
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHAST",[2423.2007],0)  // Ghast
    CreateCreature("GHAST",[2423.2007],0)  // Ghast
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHAST",[2423.2007],0)  // Ghast
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHAST",[2423.2007],0)  // Ghast
    CreateCreature("GHAST",[2423.2007],0)  // Ghast
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIM01",[2423.2007],0)  // Vampire Male
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIF01",[2423.2007],0)  // Vampire Female
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIM01",[2423.2007],0)  // Vampire Male
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIF01",[2423.2007],0)  // Vampire Female
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIM01",[2423.2007],0)  // Vampire Male
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIF01",[2423.2007],0)  // Vampire Female
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIM01",[2423.2007],0)  // Vampire Male
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIF01",[2423.2007],0)  // Vampire Female
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIM01",[2423.2007],0)  // Vampire Male
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIF01",[2423.2007],0)  // Vampire Female
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIM01",[2423.2007],0)  // Vampire Male
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIF01",[2423.2007],0)  // Vampire Female
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIM01",[2423.2007],0)  // Vampire Male
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIF01",[2423.2007],0)  // Vampire Female
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIM01",[2423.2007],0)  // Vampire Male
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIF01",[2423.2007],0)  // Vampire Female
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIM01",[2423.2007],0)  // Vampire Male
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIF01",[2423.2007],0)  // Vampire Female
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIM01",[2423.2007],0)  // Vampire Male
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIF01",[2423.2007],0)  // Vampire Female
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIM01",[2423.2007],0)  // Vampire Male
    CreateCreature("VAMPIF01",[2423.2007],0)  // Vampire Female
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIM01",[2423.2007],0)  // Vampire Male
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIF01",[2423.2007],0)  // Vampire Female
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIM01",[2423.2007],0)  // Vampire Male
    CreateCreature("VAMPIF01",[2423.2007],0)  // Vampire Female
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIM01",[2423.2007],0)  // Vampire Male
    CreateCreature("VAMPIF01",[2423.2007],0)  // Vampire Female
    CreateCreature("VAMPIF01",[2423.2007],0)  // Vampire Female
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIM01",[2423.2007],0)  // Vampire Male
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIF01",[2423.2007],0)  // Vampire Female
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #14
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIM01",[2423.2007],0)  // Vampire Male
    CreateCreature("VAMPIF01",[2423.2007],0)  // Vampire Female
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #6
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIM01",[2423.2007],0)  // Vampire Male
    CreateCreature("VAMPIF01",[2423.2007],0)  // Vampire Female
    CreateCreature("VAMPIF01",[2423.2007],0)  // Vampire Female
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END




IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #90
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHOUL",[2423.2007],0)  // Ghoul
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #90
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHOUL",[2423.2007],0)  // Ghoul
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #90
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHOUL",[2423.2007],0)  // Ghoul
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #90
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHOUL",[2423.2007],0)  // Ghoul
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #90
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHOUL",[2423.2007],0)  // Ghoul
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #90
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHOUL",[2423.2007],0)  // Ghoul
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #80
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHOUL",[2423.2007],0)  // Ghoul
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #80
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHOUL",[2423.2007],0)  // Ghoul
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #80
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHOUL",[2423.2007],0)  // Ghoul
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHOUL",[2423.2007],0)  // Ghoul
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHOUL",[2423.2007],0)  // Ghoul
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHOUL",[2423.2007],0)  // Ghoul
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #25
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHOUL",[2423.2007],0)  // Ghoul
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #25
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHOUL",[2423.2007],0)  // Ghoul
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #25
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHOUL",[2423.2007],0)  // Ghoul
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #25
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHOUL",[2423.2007],0)  // Ghoul
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHOUL",[2423.2007],0)  // Ghoul
    CreateCreature("GHOUL",[2423.2007],0)  // Ghoul
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #25
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHOUL",[2423.2007],0)  // Ghoul
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHOUL",[2423.2007],0)  // Ghoul
    CreateCreature("GHOUL",[2423.2007],0)  // Ghoul
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    CreateCreature("ZOMBIE",[2423.2007],0)  // Zombie
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #35
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHOUL",[2423.2007],0)  // Ghoul
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #35
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHOUL",[2423.2007],0)  // Ghoul
    CreateCreature("GHOUL",[2423.2007],0)  // Ghoul
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #60
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHAST",[2423.2007],0)  // Ghast
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #60
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHAST",[2423.2007],0)  // Ghast
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #60
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHAST",[2423.2007],0)  // Ghast
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHAST",[2423.2007],0)  // Ghast
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHAST",[2423.2007],0)  // Ghast
    CreateCreature("GHAST",[2423.2007],0)  // Ghast
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHAST",[2423.2007],0)  // Ghast
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHAST",[2423.2007],0)  // Ghast
    CreateCreature("GHAST",[2423.2007],0)  // Ghast
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHAST",[2423.2007],0)  // Ghast
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("GHAST",[2423.2007],0)  // Ghast
    CreateCreature("GHAST",[2423.2007],0)  // Ghast
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIM01",[2423.2007],0)  // Vampire Male
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIF01",[2423.2007],0)  // Vampire Female
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIM01",[2423.2007],0)  // Vampire Male
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIF01",[2423.2007],0)  // Vampire Female
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIM01",[2423.2007],0)  // Vampire Male
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIF01",[2423.2007],0)  // Vampire Female
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIM01",[2423.2007],0)  // Vampire Male
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIF01",[2423.2007],0)  // Vampire Female
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIM01",[2423.2007],0)  // Vampire Male
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIF01",[2423.2007],0)  // Vampire Female
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIM01",[2423.2007],0)  // Vampire Male
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIF01",[2423.2007],0)  // Vampire Female
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIM01",[2423.2007],0)  // Vampire Male
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIF01",[2423.2007],0)  // Vampire Female
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIM01",[2423.2007],0)  // Vampire Male
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIF01",[2423.2007],0)  // Vampire Female
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIM01",[2423.2007],0)  // Vampire Male
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIF01",[2423.2007],0)  // Vampire Female
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIM01",[2423.2007],0)  // Vampire Male
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIF01",[2423.2007],0)  // Vampire Female
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIM01",[2423.2007],0)  // Vampire Male
    CreateCreature("VAMPIF01",[2423.2007],0)  // Vampire Female
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIM01",[2423.2007],0)  // Vampire Male
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIF01",[2423.2007],0)  // Vampire Female
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIM01",[2423.2007],0)  // Vampire Male
    CreateCreature("VAMPIF01",[2423.2007],0)  // Vampire Female
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIM01",[2423.2007],0)  // Vampire Male
    CreateCreature("VAMPIF01",[2423.2007],0)  // Vampire Female
    CreateCreature("VAMPIF01",[2423.2007],0)  // Vampire Female
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset24232007","AR7223",0)
  Global("RandomSet24232007_3","AR7223",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("SHADOW01",[2423.2007],0)  // Shadow
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    CreateCreature("WRAITH01",[2423.2007],0)  // Wraith
    CreateCreature("NEVM1",[2423.2007],0)  // Wight
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIM01",[2423.2007],0)  // Vampire Male
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIF01",[2423.2007],0)  // Vampire Female
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #14
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIM01",[2423.2007],0)  // Vampire Male
    CreateCreature("VAMPIF01",[2423.2007],0)  // Vampire Female
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
  RESPONSE #6
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("VAMPIM01",[2423.2007],0)  // Vampire Male
    CreateCreature("VAMPIF01",[2423.2007],0)  // Vampire Female
    CreateCreature("VAMPIF01",[2423.2007],0)  // Vampire Female
    SetGlobalTimer("012324232007","AR7223",EIGHT_HOURS)
END



IF
  !Range([PC],35)
  Global("SpawnReset24232007","AR7223",1)
  GlobalTimerExpired("012324232007","AR7223")
THEN
  RESPONSE #100
    SetGlobal("SpawnReset24232007","AR7223",0)
    SetGlobal("RandomBeenSet24232007","AR7223",0)
    SetGlobal("RandomSet24232007_3","AR7223",0)
END

IF
  Range([PC],35)
  Global("SpawnReset24232007","AR7223",0)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset24232007","AR7223",1)
    CreateCreature("SKELET_B",[2423.2007],0)  // ~Skeleton~
    SetGlobalTimer("012324232007","AR7223",2400)
END

