IF
  RandomNum(1,1)
  Global("RandomSet36841064_2","AR7325",0)
  Global("RandomBeenSet36841064","AR7325",0)
THEN
  RESPONSE #100
    SetGlobal("RandomSet36841064_2","AR7325",1)
    SetGlobal("RandomBeenSet36841064","AR7325",1)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #15
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #4
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #4
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END



IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    CreateCreature("JELGRE01",[3684.1064],0)  // Green Slime
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #15
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELGRA01",[3684.1064],0)  // Gray Ooze
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #4
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset36841064","AR7325",0)
  Global("RandomSet36841064_2","AR7325",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    CreateCreature("SICKRAT",[3684.1064],0)  // Diseased Rat
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36841064","AR7325",1)
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #4
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[3684.1064],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    CreateCreature("JELMUS01",[3684.1064],0)  // Mustard Jelly
    SetGlobalTimer("022536841064","AR7325",EIGHT_HOURS)
END



IF
  !Range([PC],35)
  Global("SpawnReset36841064","AR7325",1)
  GlobalTimerExpired("022536841064","AR7325")
THEN
  RESPONSE #100
    SetGlobal("SpawnReset36841064","AR7325",0)
    SetGlobal("RandomBeenSet36841064","AR7325",0)
    SetGlobal("RandomSet36841064_2","AR7325",0)
END

IF
  Range([PC],35)
  Global("SpawnReset36841064","AR7325",0)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset36841064","AR7325",1)
    CreateCreature("JELLGR",[3684.1064],0)  // ~Gray Ooze~
    SetGlobalTimer("022536841064","AR7325",2400)
END

