IF
  Global("RandomBeenSet14351632","%ESewers%",0)
THEN
  RESPONSE %spawnRem%
    SetGlobal("RandomBeenSet14351632","%ESewers%",1)
    SetGlobal("SpawnReset14351632","%ESewers%",1)
RESPONSE %spawnPerc%
    Continue()
END
//Spawnpoint % code above

IF
  RandomNum(1,1)
  Global("RandomSet14351632_0","%ESewers%",0)
  Global("RandomBeenSet14351632","%ESewers%",0)
THEN
  RESPONSE #100
    SetGlobal("RandomSet14351632_0","%ESewers%",1)
    SetGlobal("RandomBeenSet14351632","%ESewers%",1)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #15
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #4
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #4
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END



IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #50
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    CreateCreature("JELGRE01",[1435.1632],0)  // Green Slime
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #15
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELGRA01",[1435.1632],0)  // Gray Ooze
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #4
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset14351632","%ESewers%",0)
  Global("RandomSet14351632_0","%ESewers%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    CreateCreature("SICKRAT",[1435.1632],0)  // Diseased Rat
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #4
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELOCH01",[1435.1632],0)  // Ochre Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    CreateCreature("JELMUS01",[1435.1632],0)  // Mustard Jelly
    SetGlobalTimer("022614351632","%ESewers%",EIGHT_HOURS)
END



IF
  !Range([PC],35)
  Global("SpawnReset14351632","%ESewers%",1)
  GlobalTimerExpired("022614351632","%ESewers%")
THEN
  RESPONSE #100
    SetGlobal("SpawnReset14351632","%ESewers%",0)
    SetGlobal("RandomBeenSet14351632","%ESewers%",0)
    SetGlobal("RandomSet14351632_0","%ESewers%",0)
END

IF
  Range([PC],35)
  Global("SpawnReset14351632","%ESewers%",0)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset14351632","%ESewers%",1)
    CreateCreature("CARRIO",[1435.1632],0)  // ~Carrion Crawler~
    SetGlobalTimer("022614351632","%ESewers%",2400)
END

