IF
  Global("RandomBeenSet36482944","%DurlagsTower_D4%",0)
THEN
  RESPONSE %spawnRem%
    SetGlobal("RandomBeenSet36482944","%DurlagsTower_D4%",1)
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
RESPONSE %spawnPerc%
    Continue()
END
//Spawnpoint % code above

IF
  RandomNum(1,1)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",0)
  Global("RandomBeenSet36482944","%DurlagsTower_D4%",0)
THEN
  RESPONSE #100
    SetGlobal("RandomSet36482944_0","%DurlagsTower_D4%",1)
    SetGlobal("RandomBeenSet36482944","%DurlagsTower_D4%",1)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #60
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPLIG01",[3648.2944],0)  // Lightning Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPAIR01",[3648.2944],0)  // Air Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #60
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPLIG01",[3648.2944],0)  // Lightning Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPAIR01",[3648.2944],0)  // Air Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #60
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPLIG01",[3648.2944],0)  // Lightning Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPAIR01",[3648.2944],0)  // Air Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #60
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPLIG01",[3648.2944],0)  // Lightning Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPAIR01",[3648.2944],0)  // Air Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #60
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPLIG01",[3648.2944],0)  // Lightning Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPAIR01",[3648.2944],0)  // Air Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #60
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPLIG01",[3648.2944],0)  // Lightning Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPAIR01",[3648.2944],0)  // Air Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPLIG01",[3648.2944],0)  // Lightning Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPAIR01",[3648.2944],0)  // Air Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPLIG01",[3648.2944],0)  // Lightning Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPAIR01",[3648.2944],0)  // Air Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPLIG01",[3648.2944],0)  // Lightning Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPAIR01",[3648.2944],0)  // Air Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPLIG01",[3648.2944],0)  // Lightning Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPAIR01",[3648.2944],0)  // Air Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPLIG01",[3648.2944],0)  // Lightning Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPAIR01",[3648.2944],0)  // Air Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #25
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPLIG01",[3648.2944],0)  // Lightning Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPLIG01",[3648.2944],0)  // Lightning Mephit
    CreateCreature("MEPLIG01",[3648.2944],0)  // Lightning Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPAIR01",[3648.2944],0)  // Air Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPDUS01",[3648.2944],0)  // Dust Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSMO01",[3648.2944],0)  // Smoke Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPOOZ01",[3648.2944],0)  // Ooze Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPDUS01",[3648.2944],0)  // Dust Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSMO01",[3648.2944],0)  // Smoke Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPOOZ01",[3648.2944],0)  // Ooze Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPDUS01",[3648.2944],0)  // Dust Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSMO01",[3648.2944],0)  // Smoke Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPOOZ01",[3648.2944],0)  // Ooze Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPDUS01",[3648.2944],0)  // Dust Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSMO01",[3648.2944],0)  // Smoke Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPOOZ01",[3648.2944],0)  // Ooze Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPDUS01",[3648.2944],0)  // Dust Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSMO01",[3648.2944],0)  // Smoke Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPOOZ01",[3648.2944],0)  // Ooze Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPDUS01",[3648.2944],0)  // Dust Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSMO01",[3648.2944],0)  // Smoke Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPOOZ01",[3648.2944],0)  // Ooze Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPDUS01",[3648.2944],0)  // Dust Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSMO01",[3648.2944],0)  // Smoke Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPOOZ01",[3648.2944],0)  // Ooze Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPDUS01",[3648.2944],0)  // Dust Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSMO01",[3648.2944],0)  // Smoke Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPOOZ01",[3648.2944],0)  // Ooze Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPDUS01",[3648.2944],0)  // Dust Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSMO01",[3648.2944],0)  // Smoke Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPOOZ01",[3648.2944],0)  // Ooze Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPDUS01",[3648.2944],0)  // Dust Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPDUS01",[3648.2944],0)  // Dust Mephit
    CreateCreature("MEPDUS01",[3648.2944],0)  // Dust Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSMO01",[3648.2944],0)  // Smoke Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSMO01",[3648.2944],0)  // Smoke Mephit
    CreateCreature("MEPSMO01",[3648.2944],0)  // Smoke Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPOOZ01",[3648.2944],0)  // Ooze Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPOOZ01",[3648.2944],0)  // Ooze Mephit
    CreateCreature("MEPOOZ01",[3648.2944],0)  // Ooze Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPDUS01",[3648.2944],0)  // Dust Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPDUS01",[3648.2944],0)  // Dust Mephit
    CreateCreature("MEPDUS01",[3648.2944],0)  // Dust Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSMO01",[3648.2944],0)  // Smoke Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSMO01",[3648.2944],0)  // Smoke Mephit
    CreateCreature("MEPSMO01",[3648.2944],0)  // Smoke Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPOOZ01",[3648.2944],0)  // Ooze Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPOOZ01",[3648.2944],0)  // Ooze Mephit
    CreateCreature("MEPOOZ01",[3648.2944],0)  // Ooze Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPDUS01",[3648.2944],0)  // Dust Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPDUS01",[3648.2944],0)  // Dust Mephit
    CreateCreature("MEPDUS01",[3648.2944],0)  // Dust Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSMO01",[3648.2944],0)  // Smoke Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSMO01",[3648.2944],0)  // Smoke Mephit
    CreateCreature("MEPSMO01",[3648.2944],0)  // Smoke Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPOOZ01",[3648.2944],0)  // Ooze Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPOOZ01",[3648.2944],0)  // Ooze Mephit
    CreateCreature("MEPOOZ01",[3648.2944],0)  // Ooze Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIN01",[3648.2944],0)  // Mineral Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSTE01",[3648.2944],0)  // Steam Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIN01",[3648.2944],0)  // Mineral Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSTE01",[3648.2944],0)  // Steam Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIN01",[3648.2944],0)  // Mineral Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSTE01",[3648.2944],0)  // Steam Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #15
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIN01",[3648.2944],0)  // Mineral Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIN01",[3648.2944],0)  // Mineral Mephit
    CreateCreature("MEPMIN01",[3648.2944],0)  // Mineral Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSTE01",[3648.2944],0)  // Steam Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSTE01",[3648.2944],0)  // Steam Mephit
    CreateCreature("MEPSTE01",[3648.2944],0)  // Steam Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIN01",[3648.2944],0)  // Mineral Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIN01",[3648.2944],0)  // Mineral Mephit
    CreateCreature("MEPMIN01",[3648.2944],0)  // Mineral Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSTE01",[3648.2944],0)  // Steam Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSTE01",[3648.2944],0)  // Steam Mephit
    CreateCreature("MEPSTE01",[3648.2944],0)  // Steam Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #15
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIN01",[3648.2944],0)  // Mineral Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIN01",[3648.2944],0)  // Mineral Mephit
    CreateCreature("MEPMIN01",[3648.2944],0)  // Mineral Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSTE01",[3648.2944],0)  // Steam Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSTE01",[3648.2944],0)  // Steam Mephit
    CreateCreature("MEPSTE01",[3648.2944],0)  // Steam Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIN01",[3648.2944],0)  // Mineral Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSTE01",[3648.2944],0)  // Steam Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIN01",[3648.2944],0)  // Mineral Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSTE01",[3648.2944],0)  // Steam Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIN01",[3648.2944],0)  // Mineral Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSTE01",[3648.2944],0)  // Steam Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #15
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIN01",[3648.2944],0)  // Mineral Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIN01",[3648.2944],0)  // Mineral Mephit
    CreateCreature("MEPMIN01",[3648.2944],0)  // Mineral Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSTE01",[3648.2944],0)  // Steam Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSTE01",[3648.2944],0)  // Steam Mephit
    CreateCreature("MEPSTE01",[3648.2944],0)  // Steam Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIN01",[3648.2944],0)  // Mineral Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIN01",[3648.2944],0)  // Mineral Mephit
    CreateCreature("MEPMIN01",[3648.2944],0)  // Mineral Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSTE01",[3648.2944],0)  // Steam Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSTE01",[3648.2944],0)  // Steam Mephit
    CreateCreature("MEPSTE01",[3648.2944],0)  // Steam Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #15
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIN01",[3648.2944],0)  // Mineral Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIN01",[3648.2944],0)  // Mineral Mephit
    CreateCreature("MEPMIN01",[3648.2944],0)  // Mineral Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSTE01",[3648.2944],0)  // Steam Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSTE01",[3648.2944],0)  // Steam Mephit
    CreateCreature("MEPSTE01",[3648.2944],0)  // Steam Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END



IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #60
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPLIG01",[3648.2944],0)  // Lightning Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPAIR01",[3648.2944],0)  // Air Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #60
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPLIG01",[3648.2944],0)  // Lightning Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPAIR01",[3648.2944],0)  // Air Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #60
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPLIG01",[3648.2944],0)  // Lightning Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPAIR01",[3648.2944],0)  // Air Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #60
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPLIG01",[3648.2944],0)  // Lightning Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPAIR01",[3648.2944],0)  // Air Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #60
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPLIG01",[3648.2944],0)  // Lightning Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPAIR01",[3648.2944],0)  // Air Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #60
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPLIG01",[3648.2944],0)  // Lightning Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPAIR01",[3648.2944],0)  // Air Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPLIG01",[3648.2944],0)  // Lightning Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPAIR01",[3648.2944],0)  // Air Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPLIG01",[3648.2944],0)  // Lightning Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPAIR01",[3648.2944],0)  // Air Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPLIG01",[3648.2944],0)  // Lightning Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPAIR01",[3648.2944],0)  // Air Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPLIG01",[3648.2944],0)  // Lightning Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPAIR01",[3648.2944],0)  // Air Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPLIG01",[3648.2944],0)  // Lightning Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPAIR01",[3648.2944],0)  // Air Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #25
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPLIG01",[3648.2944],0)  // Lightning Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPLIG01",[3648.2944],0)  // Lightning Mephit
    CreateCreature("MEPLIG01",[3648.2944],0)  // Lightning Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPAIR01",[3648.2944],0)  // Air Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPDUS01",[3648.2944],0)  // Dust Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSMO01",[3648.2944],0)  // Smoke Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPOOZ01",[3648.2944],0)  // Ooze Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPDUS01",[3648.2944],0)  // Dust Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSMO01",[3648.2944],0)  // Smoke Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPOOZ01",[3648.2944],0)  // Ooze Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPDUS01",[3648.2944],0)  // Dust Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSMO01",[3648.2944],0)  // Smoke Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPOOZ01",[3648.2944],0)  // Ooze Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPDUS01",[3648.2944],0)  // Dust Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSMO01",[3648.2944],0)  // Smoke Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPOOZ01",[3648.2944],0)  // Ooze Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPDUS01",[3648.2944],0)  // Dust Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSMO01",[3648.2944],0)  // Smoke Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPOOZ01",[3648.2944],0)  // Ooze Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPDUS01",[3648.2944],0)  // Dust Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSMO01",[3648.2944],0)  // Smoke Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPOOZ01",[3648.2944],0)  // Ooze Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPDUS01",[3648.2944],0)  // Dust Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSMO01",[3648.2944],0)  // Smoke Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPOOZ01",[3648.2944],0)  // Ooze Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPDUS01",[3648.2944],0)  // Dust Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSMO01",[3648.2944],0)  // Smoke Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPOOZ01",[3648.2944],0)  // Ooze Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPDUS01",[3648.2944],0)  // Dust Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSMO01",[3648.2944],0)  // Smoke Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPOOZ01",[3648.2944],0)  // Ooze Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPDUS01",[3648.2944],0)  // Dust Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPDUS01",[3648.2944],0)  // Dust Mephit
    CreateCreature("MEPDUS01",[3648.2944],0)  // Dust Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSMO01",[3648.2944],0)  // Smoke Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSMO01",[3648.2944],0)  // Smoke Mephit
    CreateCreature("MEPSMO01",[3648.2944],0)  // Smoke Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPOOZ01",[3648.2944],0)  // Ooze Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPOOZ01",[3648.2944],0)  // Ooze Mephit
    CreateCreature("MEPOOZ01",[3648.2944],0)  // Ooze Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPDUS01",[3648.2944],0)  // Dust Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPDUS01",[3648.2944],0)  // Dust Mephit
    CreateCreature("MEPDUS01",[3648.2944],0)  // Dust Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSMO01",[3648.2944],0)  // Smoke Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSMO01",[3648.2944],0)  // Smoke Mephit
    CreateCreature("MEPSMO01",[3648.2944],0)  // Smoke Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPOOZ01",[3648.2944],0)  // Ooze Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPOOZ01",[3648.2944],0)  // Ooze Mephit
    CreateCreature("MEPOOZ01",[3648.2944],0)  // Ooze Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    CreateCreature("MEPFIR01",[3648.2944],0)  // Fire Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPDUS01",[3648.2944],0)  // Dust Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPDUS01",[3648.2944],0)  // Dust Mephit
    CreateCreature("MEPDUS01",[3648.2944],0)  // Dust Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSMO01",[3648.2944],0)  // Smoke Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSMO01",[3648.2944],0)  // Smoke Mephit
    CreateCreature("MEPSMO01",[3648.2944],0)  // Smoke Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    CreateCreature("MEPICE01",[3648.2944],0)  // Ice Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPOOZ01",[3648.2944],0)  // Ooze Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPOOZ01",[3648.2944],0)  // Ooze Mephit
    CreateCreature("MEPOOZ01",[3648.2944],0)  // Ooze Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIN01",[3648.2944],0)  // Mineral Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSTE01",[3648.2944],0)  // Steam Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIN01",[3648.2944],0)  // Mineral Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSTE01",[3648.2944],0)  // Steam Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIN01",[3648.2944],0)  // Mineral Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSTE01",[3648.2944],0)  // Steam Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #15
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIN01",[3648.2944],0)  // Mineral Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIN01",[3648.2944],0)  // Mineral Mephit
    CreateCreature("MEPMIN01",[3648.2944],0)  // Mineral Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSTE01",[3648.2944],0)  // Steam Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSTE01",[3648.2944],0)  // Steam Mephit
    CreateCreature("MEPSTE01",[3648.2944],0)  // Steam Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIN01",[3648.2944],0)  // Mineral Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIN01",[3648.2944],0)  // Mineral Mephit
    CreateCreature("MEPMIN01",[3648.2944],0)  // Mineral Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSTE01",[3648.2944],0)  // Steam Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSTE01",[3648.2944],0)  // Steam Mephit
    CreateCreature("MEPSTE01",[3648.2944],0)  // Steam Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #15
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIN01",[3648.2944],0)  // Mineral Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIN01",[3648.2944],0)  // Mineral Mephit
    CreateCreature("MEPMIN01",[3648.2944],0)  // Mineral Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSTE01",[3648.2944],0)  // Steam Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSTE01",[3648.2944],0)  // Steam Mephit
    CreateCreature("MEPSTE01",[3648.2944],0)  // Steam Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIN01",[3648.2944],0)  // Mineral Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSTE01",[3648.2944],0)  // Steam Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIN01",[3648.2944],0)  // Mineral Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSTE01",[3648.2944],0)  // Steam Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIN01",[3648.2944],0)  // Mineral Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSTE01",[3648.2944],0)  // Steam Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #15
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIN01",[3648.2944],0)  // Mineral Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIN01",[3648.2944],0)  // Mineral Mephit
    CreateCreature("MEPMIN01",[3648.2944],0)  // Mineral Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSTE01",[3648.2944],0)  // Steam Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSTE01",[3648.2944],0)  // Steam Mephit
    CreateCreature("MEPSTE01",[3648.2944],0)  // Steam Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIN01",[3648.2944],0)  // Mineral Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIN01",[3648.2944],0)  // Mineral Mephit
    CreateCreature("MEPMIN01",[3648.2944],0)  // Mineral Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSTE01",[3648.2944],0)  // Steam Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSTE01",[3648.2944],0)  // Steam Mephit
    CreateCreature("MEPSTE01",[3648.2944],0)  // Steam Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
  Global("RandomSet36482944_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #15
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[3648.2944],0)  // Magma Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[3648.2944],0)  // Mist Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIN01",[3648.2944],0)  // Mineral Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPMIN01",[3648.2944],0)  // Mineral Mephit
    CreateCreature("MEPMIN01",[3648.2944],0)  // Mineral Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSTE01",[3648.2944],0)  // Steam Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("MEPSTE01",[3648.2944],0)  // Steam Mephit
    CreateCreature("MEPSTE01",[3648.2944],0)  // Steam Mephit
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",EIGHT_HOURS)
END


IF
  !Range([PC],35)
  Global("SpawnReset36482944","%DurlagsTower_D4%",1)
  GlobalTimerExpired("051436482944","%DurlagsTower_D4%")
THEN
  RESPONSE #100
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",0)
    SetGlobal("RandomBeenSet36482944","%DurlagsTower_D4%",0)
    SetGlobal("RandomSet36482944_0","%DurlagsTower_D4%",0)
END

IF
  Range([PC],35)
  Global("SpawnReset36482944","%DurlagsTower_D4%",0)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset36482944","%DurlagsTower_D4%",1)
    CreateCreature("GHOULLOR",[3648.2944],0)  // ~Greater Ghoul~
    SetGlobalTimer("051436482944","%DurlagsTower_D4%",2400)
END

