IF
  RandomNum(1,1)
  Global("RandomSet18473004_0","ARD014",0)
  Global("RandomBeenSet18473004","ARD014",0)
THEN
  RESPONSE #100
    SetGlobal("RandomSet18473004_0","ARD014",1)
    SetGlobal("RandomBeenSet18473004","ARD014",1)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #60
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPLIG01",[1847.3004],0)  // Lightning Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPAIR01",[1847.3004],0)  // Air Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #60
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPLIG01",[1847.3004],0)  // Lightning Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPAIR01",[1847.3004],0)  // Air Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #60
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPLIG01",[1847.3004],0)  // Lightning Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPAIR01",[1847.3004],0)  // Air Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #60
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPLIG01",[1847.3004],0)  // Lightning Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPAIR01",[1847.3004],0)  // Air Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #60
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPLIG01",[1847.3004],0)  // Lightning Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPAIR01",[1847.3004],0)  // Air Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #60
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPLIG01",[1847.3004],0)  // Lightning Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPAIR01",[1847.3004],0)  // Air Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPLIG01",[1847.3004],0)  // Lightning Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPAIR01",[1847.3004],0)  // Air Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPLIG01",[1847.3004],0)  // Lightning Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPAIR01",[1847.3004],0)  // Air Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPLIG01",[1847.3004],0)  // Lightning Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPAIR01",[1847.3004],0)  // Air Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPLIG01",[1847.3004],0)  // Lightning Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPAIR01",[1847.3004],0)  // Air Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPLIG01",[1847.3004],0)  // Lightning Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPAIR01",[1847.3004],0)  // Air Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #25
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPLIG01",[1847.3004],0)  // Lightning Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPLIG01",[1847.3004],0)  // Lightning Mephit
    CreateCreature("MEPLIG01",[1847.3004],0)  // Lightning Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPAIR01",[1847.3004],0)  // Air Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPDUS01",[1847.3004],0)  // Dust Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSMO01",[1847.3004],0)  // Smoke Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPOOZ01",[1847.3004],0)  // Ooze Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPDUS01",[1847.3004],0)  // Dust Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSMO01",[1847.3004],0)  // Smoke Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPOOZ01",[1847.3004],0)  // Ooze Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPDUS01",[1847.3004],0)  // Dust Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSMO01",[1847.3004],0)  // Smoke Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPOOZ01",[1847.3004],0)  // Ooze Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPDUS01",[1847.3004],0)  // Dust Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSMO01",[1847.3004],0)  // Smoke Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPOOZ01",[1847.3004],0)  // Ooze Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPDUS01",[1847.3004],0)  // Dust Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSMO01",[1847.3004],0)  // Smoke Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPOOZ01",[1847.3004],0)  // Ooze Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPDUS01",[1847.3004],0)  // Dust Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSMO01",[1847.3004],0)  // Smoke Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPOOZ01",[1847.3004],0)  // Ooze Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPDUS01",[1847.3004],0)  // Dust Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSMO01",[1847.3004],0)  // Smoke Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPOOZ01",[1847.3004],0)  // Ooze Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPDUS01",[1847.3004],0)  // Dust Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSMO01",[1847.3004],0)  // Smoke Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPOOZ01",[1847.3004],0)  // Ooze Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPDUS01",[1847.3004],0)  // Dust Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSMO01",[1847.3004],0)  // Smoke Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPOOZ01",[1847.3004],0)  // Ooze Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPDUS01",[1847.3004],0)  // Dust Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPDUS01",[1847.3004],0)  // Dust Mephit
    CreateCreature("MEPDUS01",[1847.3004],0)  // Dust Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSMO01",[1847.3004],0)  // Smoke Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSMO01",[1847.3004],0)  // Smoke Mephit
    CreateCreature("MEPSMO01",[1847.3004],0)  // Smoke Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPOOZ01",[1847.3004],0)  // Ooze Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPOOZ01",[1847.3004],0)  // Ooze Mephit
    CreateCreature("MEPOOZ01",[1847.3004],0)  // Ooze Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPDUS01",[1847.3004],0)  // Dust Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPDUS01",[1847.3004],0)  // Dust Mephit
    CreateCreature("MEPDUS01",[1847.3004],0)  // Dust Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSMO01",[1847.3004],0)  // Smoke Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSMO01",[1847.3004],0)  // Smoke Mephit
    CreateCreature("MEPSMO01",[1847.3004],0)  // Smoke Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPOOZ01",[1847.3004],0)  // Ooze Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPOOZ01",[1847.3004],0)  // Ooze Mephit
    CreateCreature("MEPOOZ01",[1847.3004],0)  // Ooze Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPDUS01",[1847.3004],0)  // Dust Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPDUS01",[1847.3004],0)  // Dust Mephit
    CreateCreature("MEPDUS01",[1847.3004],0)  // Dust Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSMO01",[1847.3004],0)  // Smoke Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSMO01",[1847.3004],0)  // Smoke Mephit
    CreateCreature("MEPSMO01",[1847.3004],0)  // Smoke Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPOOZ01",[1847.3004],0)  // Ooze Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPOOZ01",[1847.3004],0)  // Ooze Mephit
    CreateCreature("MEPOOZ01",[1847.3004],0)  // Ooze Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIN01",[1847.3004],0)  // Mineral Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSTE01",[1847.3004],0)  // Steam Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIN01",[1847.3004],0)  // Mineral Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSTE01",[1847.3004],0)  // Steam Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIN01",[1847.3004],0)  // Mineral Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSTE01",[1847.3004],0)  // Steam Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #15
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIN01",[1847.3004],0)  // Mineral Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIN01",[1847.3004],0)  // Mineral Mephit
    CreateCreature("MEPMIN01",[1847.3004],0)  // Mineral Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSTE01",[1847.3004],0)  // Steam Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSTE01",[1847.3004],0)  // Steam Mephit
    CreateCreature("MEPSTE01",[1847.3004],0)  // Steam Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIN01",[1847.3004],0)  // Mineral Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIN01",[1847.3004],0)  // Mineral Mephit
    CreateCreature("MEPMIN01",[1847.3004],0)  // Mineral Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSTE01",[1847.3004],0)  // Steam Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSTE01",[1847.3004],0)  // Steam Mephit
    CreateCreature("MEPSTE01",[1847.3004],0)  // Steam Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #15
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIN01",[1847.3004],0)  // Mineral Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIN01",[1847.3004],0)  // Mineral Mephit
    CreateCreature("MEPMIN01",[1847.3004],0)  // Mineral Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSTE01",[1847.3004],0)  // Steam Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSTE01",[1847.3004],0)  // Steam Mephit
    CreateCreature("MEPSTE01",[1847.3004],0)  // Steam Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIN01",[1847.3004],0)  // Mineral Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSTE01",[1847.3004],0)  // Steam Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIN01",[1847.3004],0)  // Mineral Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSTE01",[1847.3004],0)  // Steam Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIN01",[1847.3004],0)  // Mineral Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSTE01",[1847.3004],0)  // Steam Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #15
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIN01",[1847.3004],0)  // Mineral Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIN01",[1847.3004],0)  // Mineral Mephit
    CreateCreature("MEPMIN01",[1847.3004],0)  // Mineral Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSTE01",[1847.3004],0)  // Steam Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSTE01",[1847.3004],0)  // Steam Mephit
    CreateCreature("MEPSTE01",[1847.3004],0)  // Steam Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIN01",[1847.3004],0)  // Mineral Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIN01",[1847.3004],0)  // Mineral Mephit
    CreateCreature("MEPMIN01",[1847.3004],0)  // Mineral Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSTE01",[1847.3004],0)  // Steam Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSTE01",[1847.3004],0)  // Steam Mephit
    CreateCreature("MEPSTE01",[1847.3004],0)  // Steam Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #15
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIN01",[1847.3004],0)  // Mineral Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIN01",[1847.3004],0)  // Mineral Mephit
    CreateCreature("MEPMIN01",[1847.3004],0)  // Mineral Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSTE01",[1847.3004],0)  // Steam Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSTE01",[1847.3004],0)  // Steam Mephit
    CreateCreature("MEPSTE01",[1847.3004],0)  // Steam Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END



IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #60
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPLIG01",[1847.3004],0)  // Lightning Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPAIR01",[1847.3004],0)  // Air Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #60
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPLIG01",[1847.3004],0)  // Lightning Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPAIR01",[1847.3004],0)  // Air Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #60
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPLIG01",[1847.3004],0)  // Lightning Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPAIR01",[1847.3004],0)  // Air Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #60
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPLIG01",[1847.3004],0)  // Lightning Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPAIR01",[1847.3004],0)  // Air Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #60
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPLIG01",[1847.3004],0)  // Lightning Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPAIR01",[1847.3004],0)  // Air Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #60
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPLIG01",[1847.3004],0)  // Lightning Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPAIR01",[1847.3004],0)  // Air Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPLIG01",[1847.3004],0)  // Lightning Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPAIR01",[1847.3004],0)  // Air Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPLIG01",[1847.3004],0)  // Lightning Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPAIR01",[1847.3004],0)  // Air Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPLIG01",[1847.3004],0)  // Lightning Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPAIR01",[1847.3004],0)  // Air Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPLIG01",[1847.3004],0)  // Lightning Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPAIR01",[1847.3004],0)  // Air Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPLIG01",[1847.3004],0)  // Lightning Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPAIR01",[1847.3004],0)  // Air Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #25
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPLIG01",[1847.3004],0)  // Lightning Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPLIG01",[1847.3004],0)  // Lightning Mephit
    CreateCreature("MEPLIG01",[1847.3004],0)  // Lightning Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPAIR01",[1847.3004],0)  // Air Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPDUS01",[1847.3004],0)  // Dust Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSMO01",[1847.3004],0)  // Smoke Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPOOZ01",[1847.3004],0)  // Ooze Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPDUS01",[1847.3004],0)  // Dust Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSMO01",[1847.3004],0)  // Smoke Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPOOZ01",[1847.3004],0)  // Ooze Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPDUS01",[1847.3004],0)  // Dust Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSMO01",[1847.3004],0)  // Smoke Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPOOZ01",[1847.3004],0)  // Ooze Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPDUS01",[1847.3004],0)  // Dust Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSMO01",[1847.3004],0)  // Smoke Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPOOZ01",[1847.3004],0)  // Ooze Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPDUS01",[1847.3004],0)  // Dust Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSMO01",[1847.3004],0)  // Smoke Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPOOZ01",[1847.3004],0)  // Ooze Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPDUS01",[1847.3004],0)  // Dust Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSMO01",[1847.3004],0)  // Smoke Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPOOZ01",[1847.3004],0)  // Ooze Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPDUS01",[1847.3004],0)  // Dust Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSMO01",[1847.3004],0)  // Smoke Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPOOZ01",[1847.3004],0)  // Ooze Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPDUS01",[1847.3004],0)  // Dust Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSMO01",[1847.3004],0)  // Smoke Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPOOZ01",[1847.3004],0)  // Ooze Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPDUS01",[1847.3004],0)  // Dust Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSMO01",[1847.3004],0)  // Smoke Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPOOZ01",[1847.3004],0)  // Ooze Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPDUS01",[1847.3004],0)  // Dust Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPDUS01",[1847.3004],0)  // Dust Mephit
    CreateCreature("MEPDUS01",[1847.3004],0)  // Dust Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSMO01",[1847.3004],0)  // Smoke Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSMO01",[1847.3004],0)  // Smoke Mephit
    CreateCreature("MEPSMO01",[1847.3004],0)  // Smoke Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPOOZ01",[1847.3004],0)  // Ooze Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPOOZ01",[1847.3004],0)  // Ooze Mephit
    CreateCreature("MEPOOZ01",[1847.3004],0)  // Ooze Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPDUS01",[1847.3004],0)  // Dust Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPDUS01",[1847.3004],0)  // Dust Mephit
    CreateCreature("MEPDUS01",[1847.3004],0)  // Dust Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSMO01",[1847.3004],0)  // Smoke Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSMO01",[1847.3004],0)  // Smoke Mephit
    CreateCreature("MEPSMO01",[1847.3004],0)  // Smoke Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPOOZ01",[1847.3004],0)  // Ooze Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPOOZ01",[1847.3004],0)  // Ooze Mephit
    CreateCreature("MEPOOZ01",[1847.3004],0)  // Ooze Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    CreateCreature("MEPFIR01",[1847.3004],0)  // Fire Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPDUS01",[1847.3004],0)  // Dust Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPDUS01",[1847.3004],0)  // Dust Mephit
    CreateCreature("MEPDUS01",[1847.3004],0)  // Dust Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSMO01",[1847.3004],0)  // Smoke Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSMO01",[1847.3004],0)  // Smoke Mephit
    CreateCreature("MEPSMO01",[1847.3004],0)  // Smoke Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    CreateCreature("MEPICE01",[1847.3004],0)  // Ice Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPOOZ01",[1847.3004],0)  // Ooze Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPOOZ01",[1847.3004],0)  // Ooze Mephit
    CreateCreature("MEPOOZ01",[1847.3004],0)  // Ooze Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIN01",[1847.3004],0)  // Mineral Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSTE01",[1847.3004],0)  // Steam Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIN01",[1847.3004],0)  // Mineral Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSTE01",[1847.3004],0)  // Steam Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIN01",[1847.3004],0)  // Mineral Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSTE01",[1847.3004],0)  // Steam Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #15
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIN01",[1847.3004],0)  // Mineral Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIN01",[1847.3004],0)  // Mineral Mephit
    CreateCreature("MEPMIN01",[1847.3004],0)  // Mineral Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSTE01",[1847.3004],0)  // Steam Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSTE01",[1847.3004],0)  // Steam Mephit
    CreateCreature("MEPSTE01",[1847.3004],0)  // Steam Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIN01",[1847.3004],0)  // Mineral Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIN01",[1847.3004],0)  // Mineral Mephit
    CreateCreature("MEPMIN01",[1847.3004],0)  // Mineral Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSTE01",[1847.3004],0)  // Steam Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSTE01",[1847.3004],0)  // Steam Mephit
    CreateCreature("MEPSTE01",[1847.3004],0)  // Steam Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #15
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIN01",[1847.3004],0)  // Mineral Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIN01",[1847.3004],0)  // Mineral Mephit
    CreateCreature("MEPMIN01",[1847.3004],0)  // Mineral Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSTE01",[1847.3004],0)  // Steam Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSTE01",[1847.3004],0)  // Steam Mephit
    CreateCreature("MEPSTE01",[1847.3004],0)  // Steam Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIN01",[1847.3004],0)  // Mineral Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSTE01",[1847.3004],0)  // Steam Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIN01",[1847.3004],0)  // Mineral Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSTE01",[1847.3004],0)  // Steam Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIN01",[1847.3004],0)  // Mineral Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSTE01",[1847.3004],0)  // Steam Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #15
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIN01",[1847.3004],0)  // Mineral Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIN01",[1847.3004],0)  // Mineral Mephit
    CreateCreature("MEPMIN01",[1847.3004],0)  // Mineral Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSTE01",[1847.3004],0)  // Steam Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSTE01",[1847.3004],0)  // Steam Mephit
    CreateCreature("MEPSTE01",[1847.3004],0)  // Steam Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIN01",[1847.3004],0)  // Mineral Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIN01",[1847.3004],0)  // Mineral Mephit
    CreateCreature("MEPMIN01",[1847.3004],0)  // Mineral Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSTE01",[1847.3004],0)  // Steam Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSTE01",[1847.3004],0)  // Steam Mephit
    CreateCreature("MEPSTE01",[1847.3004],0)  // Steam Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset18473004","ARD014",0)
  Global("RandomSet18473004_0","ARD014",1)
THEN
  RESPONSE #15
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    CreateCreature("MEPMAG01",[1847.3004],0)  // Magma Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset18473004","ARD014",1)
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    CreateCreature("MEPMIS01",[1847.3004],0)  // Mist Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIN01",[1847.3004],0)  // Mineral Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPMIN01",[1847.3004],0)  // Mineral Mephit
    CreateCreature("MEPMIN01",[1847.3004],0)  // Mineral Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSTE01",[1847.3004],0)  // Steam Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("MEPSTE01",[1847.3004],0)  // Steam Mephit
    CreateCreature("MEPSTE01",[1847.3004],0)  // Steam Mephit
    SetGlobalTimer("051418473004","ARD014",EIGHT_HOURS)
END


IF
  !Range([PC],35)
  Global("SpawnReset18473004","ARD014",1)
  GlobalTimerExpired("051418473004","ARD014")
THEN
  RESPONSE #100
    SetGlobal("SpawnReset18473004","ARD014",0)
    SetGlobal("RandomBeenSet18473004","ARD014",0)
    SetGlobal("RandomSet18473004_0","ARD014",0)
END

IF
  Range([PC],35)
  Global("SpawnReset18473004","ARD014",0)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset18473004","ARD014",1)
    CreateCreature("GHOULLOR",[1847.3004],0)  // ~Greater Ghoul~
    SetGlobalTimer("051418473004","ARD014",2400)
END

