IF
  Global("RandomBeenSet10712753","%IsleofBalduranN%",0)
THEN
  RESPONSE %spawnRem%
    SetGlobal("RandomBeenSet10712753","%IsleofBalduranN%",1)
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
RESPONSE %spawnPerc%
    Continue()
END
//Spawnpoint % code above

IF
  RandomNum(1,1)
  Global("RandomSet10712753_2","%IsleofBalduranN%",0)
  Global("RandomBeenSet10712753","%IsleofBalduranN%",0)
THEN
  RESPONSE #100
    SetGlobal("RandomSet10712753_2","%IsleofBalduranN%",1)
    SetGlobal("RandomBeenSet10712753","%IsleofBalduranN%",1)
END


IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("DEER01",[1071.2753],0)  // Deer
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("DEER01",[1071.2753],0)  // Deer
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("DEER01",[1071.2753],0)  // Deer
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("DEER01",[1071.2753],0)  // Deer
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("DEER01",[1071.2753],0)  // Deer
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("DEER01",[1071.2753],0)  // Deer
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("DEER01",[1071.2753],0)  // Deer
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("DEER01",[1071.2753],0)  // Deer
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("DEER01",[1071.2753],0)  // Deer
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("DEER01",[1071.2753],0)  // Deer
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("DEER01",[1071.2753],0)  // Deer
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("DEER01",[1071.2753],0)  // Deer
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("DEER01",[1071.2753],0)  // Deer
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("DEER01",[1071.2753],0)  // Deer
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("DEER01",[1071.2753],0)  // Deer
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("DEER01",[1071.2753],0)  // Deer
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("DEER01",[1071.2753],0)  // Deer
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #3
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #4
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("DEER01",[1071.2753],0)  // Deer
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("DEER01",[1071.2753],0)  // Deer
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("DEER01",[1071.2753],0)  // Deer
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("DEER01",[1071.2753],0)  // Deer
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("DEER01",[1071.2753],0)  // Deer
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("DEER01",[1071.2753],0)  // Deer
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("DEER01",[1071.2753],0)  // Deer
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("DEER01",[1071.2753],0)  // Deer
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("DEER01",[1071.2753],0)  // Deer
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("DEER01",[1071.2753],0)  // Deer
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("DEER01",[1071.2753],0)  // Deer
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("DEER01",[1071.2753],0)  // Deer
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("DEER01",[1071.2753],0)  // Deer
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("DEER01",[1071.2753],0)  // Deer
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("DEER01",[1071.2753],0)  // Deer
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #3
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #4
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("DEER01",[1071.2753],0)  // Deer
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("DEER01",[1071.2753],0)  // Deer
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("DEER01",[1071.2753],0)  // Deer
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("DEER01",[1071.2753],0)  // Deer
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    CreateCreature("WOLFDI",[1071.2753],0)  // Dire Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END



IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #15
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #15
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFDR01",[1071.2753],0)  // Dread Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #25
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFVA01",[1071.2753],0)  // Vampiric Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("ROGTRO",[1071.2753],0)  // Sea Troll
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #12
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #13
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFVA01",[1071.2753],0)  // Vampiric Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("ROGTRO",[1071.2753],0)  // Sea Troll
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #7
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #9
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #9
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFVA01",[1071.2753],0)  // Vampiric Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("ROGTRO",[1071.2753],0)  // Sea Troll
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #7
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #6
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #6
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #6
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFVA01",[1071.2753],0)  // Vampiric Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("ROGTRO",[1071.2753],0)  // Sea Troll
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #7
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #9
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #9
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFVA01",[1071.2753],0)  // Vampiric Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("ROGTRO",[1071.2753],0)  // Sea Troll
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #7
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #6
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #6
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #6
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFVA01",[1071.2753],0)  // Vampiric Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("ROGTRO",[1071.2753],0)  // Sea Troll
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #25
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFVA01",[1071.2753],0)  // Vampiric Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFGR01",[1071.2753],0)  // Greater Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("ROGTRO",[1071.2753],0)  // Sea Troll
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #13
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #12
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFVA01",[1071.2753],0)  // Vampiric Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFGR01",[1071.2753],0)  // Greater Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("ROGTRO",[1071.2753],0)  // Sea Troll
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #13
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #12
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFVA01",[1071.2753],0)  // Vampiric Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFGR01",[1071.2753],0)  // Greater Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("ROGTRO",[1071.2753],0)  // Sea Troll
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #7
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #6
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #6
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #6
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFVA01",[1071.2753],0)  // Vampiric Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFGR01",[1071.2753],0)  // Greater Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("ROGTRO",[1071.2753],0)  // Sea Troll
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #7
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #6
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #6
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #6
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFVA01",[1071.2753],0)  // Vampiric Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFGR01",[1071.2753],0)  // Greater Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("ROGTRO",[1071.2753],0)  // Sea Troll
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #12
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #13
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    CreateCreature("WOLFZO01",[1071.2753],0)  // Zombie Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    CreateCreature("WOLF01",[1071.2753],0)  // Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFVA01",[1071.2753],0)  // Vampiric Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFGR01",[1071.2753],0)  // Greater Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("ROGTRO",[1071.2753],0)  // Sea Troll
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFGR01",[1071.2753],0)  // Greater Wolfwere
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFVA01",[1071.2753],0)  // Vampiric Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFGR01",[1071.2753],0)  // Greater Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("ROGTRO",[1071.2753],0)  // Sea Troll
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFVA01",[1071.2753],0)  // Vampiric Wolf
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFGR01",[1071.2753],0)  // Greater Wolfwere
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFVA01",[1071.2753],0)  // Vampiric Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFGR01",[1071.2753],0)  // Greater Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("ROGTRO",[1071.2753],0)  // Sea Troll
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFVA01",[1071.2753],0)  // Vampiric Wolf
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFGR01",[1071.2753],0)  // Greater Wolfwere
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFVA01",[1071.2753],0)  // Vampiric Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFGR01",[1071.2753],0)  // Greater Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("ROGTRO",[1071.2753],0)  // Sea Troll
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFVA01",[1071.2753],0)  // Vampiric Wolf
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #15
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFGR01",[1071.2753],0)  // Greater Wolfwere
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFGR01",[1071.2753],0)  // Greater Wolfwere
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFVA01",[1071.2753],0)  // Vampiric Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFGR01",[1071.2753],0)  // Greater Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("ROGTRO",[1071.2753],0)  // Sea Troll
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFVA01",[1071.2753],0)  // Vampiric Wolf
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFVA01",[1071.2753],0)  // Vampiric Wolf
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFGR01",[1071.2753],0)  // Greater Wolfwere
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFGR01",[1071.2753],0)  // Greater Wolfwere
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFGR01",[1071.2753],0)  // Greater Wolfwere
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFVA01",[1071.2753],0)  // Vampiric Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFGR01",[1071.2753],0)  // Greater Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("ROGTRO",[1071.2753],0)  // Sea Troll
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFVA01",[1071.2753],0)  // Vampiric Wolf
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFVA01",[1071.2753],0)  // Vampiric Wolf
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
  Global("RandomSet10712753_2","%IsleofBalduranN%",1)
THEN
  RESPONSE #15
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFGR01",[1071.2753],0)  // Greater Wolfwere
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFGR01",[1071.2753],0)  // Greater Wolfwere
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFVA01",[1071.2753],0)  // Vampiric Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFVA01",[1071.2753],0)  // Vampiric Wolf
    CreateCreature("WOLFVA01",[1071.2753],0)  // Vampiric Wolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    CreateCreature("WEREWO",[1071.2753],0)  // Werewolf
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFGR01",[1071.2753],0)  // Greater Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("ROGTRO",[1071.2753],0)  // Sea Troll
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFVA01",[1071.2753],0)  // Vampiric Wolf
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFVA01",[1071.2753],0)  // Vampiric Wolf
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    CreateCreature("WOLFWE",[1071.2753],0)  // Wolfwere
    SetGlobalTimer("150010712753","%IsleofBalduranN%",EIGHT_HOURS)
END




IF
  !Range([PC],35)
  Global("SpawnReset10712753","%IsleofBalduranN%",1)
  GlobalTimerExpired("150010712753","%IsleofBalduranN%")
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",0)
    SetGlobal("RandomBeenSet10712753","%IsleofBalduranN%",0)
    SetGlobal("RandomSet10712753_2","%IsleofBalduranN%",0)
END

IF
  Range([PC],35)
  Global("SpawnReset10712753","%IsleofBalduranN%",0)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10712753","%IsleofBalduranN%",1)
    CreateCreature("WOLFWEGL",[1071.2753],0)  // ~Wolfwere~
    SetGlobalTimer("150010712753","%IsleofBalduranN%",2400)
END

