IF
  RandomNum(1,1)
  Global("RandomSet704320_1","ARW000",0)
  Global("RandomBeenSet704320","ARW000",0)
THEN
  RESPONSE #100
    SetGlobal("RandomSet704320_1","ARW000",1)
    SetGlobal("RandomBeenSet704320","ARW000",1)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("DEER01",[704.320],0)  // Deer
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("DEER01",[704.320],0)  // Deer
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("DEER01",[704.320],0)  // Deer
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("DEER01",[704.320],0)  // Deer
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("DEER01",[704.320],0)  // Deer
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("DEER01",[704.320],0)  // Deer
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("DEER01",[704.320],0)  // Deer
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("DEER01",[704.320],0)  // Deer
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("DEER01",[704.320],0)  // Deer
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("DEER01",[704.320],0)  // Deer
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("DEER01",[704.320],0)  // Deer
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("DEER01",[704.320],0)  // Deer
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("DEER01",[704.320],0)  // Deer
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("DEER01",[704.320],0)  // Deer
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("DEER01",[704.320],0)  // Deer
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("DEER01",[704.320],0)  // Deer
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("DEER01",[704.320],0)  // Deer
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #3
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #4
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("DEER01",[704.320],0)  // Deer
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("DEER01",[704.320],0)  // Deer
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("DEER01",[704.320],0)  // Deer
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("DEER01",[704.320],0)  // Deer
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("DEER01",[704.320],0)  // Deer
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("DEER01",[704.320],0)  // Deer
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("DEER01",[704.320],0)  // Deer
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("DEER01",[704.320],0)  // Deer
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("DEER01",[704.320],0)  // Deer
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("DEER01",[704.320],0)  // Deer
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("DEER01",[704.320],0)  // Deer
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("DEER01",[704.320],0)  // Deer
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("DEER01",[704.320],0)  // Deer
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("DEER01",[704.320],0)  // Deer
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("DEER01",[704.320],0)  // Deer
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #3
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #4
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("DEER01",[704.320],0)  // Deer
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("DEER01",[704.320],0)  // Deer
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("DEER01",[704.320],0)  // Deer
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("DEER01",[704.320],0)  // Deer
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    CreateCreature("WOLFDI",[704.320],0)  // Dire Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END



IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #15
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #15
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFDR01",[704.320],0)  // Dread Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #25
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFVA01",[704.320],0)  // Vampiric Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("ROGTRO",[704.320],0)  // Sea Troll
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #12
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #13
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFVA01",[704.320],0)  // Vampiric Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("ROGTRO",[704.320],0)  // Sea Troll
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #7
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #9
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #9
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFVA01",[704.320],0)  // Vampiric Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("ROGTRO",[704.320],0)  // Sea Troll
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #7
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #6
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #6
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #6
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFVA01",[704.320],0)  // Vampiric Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("ROGTRO",[704.320],0)  // Sea Troll
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #7
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #9
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #9
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFVA01",[704.320],0)  // Vampiric Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("ROGTRO",[704.320],0)  // Sea Troll
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #7
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #6
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #6
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #6
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFVA01",[704.320],0)  // Vampiric Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("ROGTRO",[704.320],0)  // Sea Troll
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #25
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFVA01",[704.320],0)  // Vampiric Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFGR01",[704.320],0)  // Greater Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("ROGTRO",[704.320],0)  // Sea Troll
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #13
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #12
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFVA01",[704.320],0)  // Vampiric Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFGR01",[704.320],0)  // Greater Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("ROGTRO",[704.320],0)  // Sea Troll
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #13
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #12
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFVA01",[704.320],0)  // Vampiric Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFGR01",[704.320],0)  // Greater Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("ROGTRO",[704.320],0)  // Sea Troll
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #7
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #6
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #6
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #6
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFVA01",[704.320],0)  // Vampiric Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFGR01",[704.320],0)  // Greater Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("ROGTRO",[704.320],0)  // Sea Troll
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #7
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #6
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #6
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #6
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFVA01",[704.320],0)  // Vampiric Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFGR01",[704.320],0)  // Greater Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("ROGTRO",[704.320],0)  // Sea Troll
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #12
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #13
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    CreateCreature("WOLFZO01",[704.320],0)  // Zombie Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    CreateCreature("WOLF01",[704.320],0)  // Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFVA01",[704.320],0)  // Vampiric Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFGR01",[704.320],0)  // Greater Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("ROGTRO",[704.320],0)  // Sea Troll
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFGR01",[704.320],0)  // Greater Wolfwere
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFVA01",[704.320],0)  // Vampiric Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFGR01",[704.320],0)  // Greater Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("ROGTRO",[704.320],0)  // Sea Troll
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFVA01",[704.320],0)  // Vampiric Wolf
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFGR01",[704.320],0)  // Greater Wolfwere
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFVA01",[704.320],0)  // Vampiric Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFGR01",[704.320],0)  // Greater Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("ROGTRO",[704.320],0)  // Sea Troll
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFVA01",[704.320],0)  // Vampiric Wolf
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFGR01",[704.320],0)  // Greater Wolfwere
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFVA01",[704.320],0)  // Vampiric Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFGR01",[704.320],0)  // Greater Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("ROGTRO",[704.320],0)  // Sea Troll
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFVA01",[704.320],0)  // Vampiric Wolf
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #15
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFGR01",[704.320],0)  // Greater Wolfwere
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFGR01",[704.320],0)  // Greater Wolfwere
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFVA01",[704.320],0)  // Vampiric Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFGR01",[704.320],0)  // Greater Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("ROGTRO",[704.320],0)  // Sea Troll
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFVA01",[704.320],0)  // Vampiric Wolf
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFVA01",[704.320],0)  // Vampiric Wolf
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFGR01",[704.320],0)  // Greater Wolfwere
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFGR01",[704.320],0)  // Greater Wolfwere
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFGR01",[704.320],0)  // Greater Wolfwere
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFVA01",[704.320],0)  // Vampiric Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFGR01",[704.320],0)  // Greater Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("ROGTRO",[704.320],0)  // Sea Troll
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFVA01",[704.320],0)  // Vampiric Wolf
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFVA01",[704.320],0)  // Vampiric Wolf
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset704320","ARW000",0)
  Global("RandomSet704320_1","ARW000",1)
THEN
  RESPONSE #15
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFGR01",[704.320],0)  // Greater Wolfwere
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFGR01",[704.320],0)  // Greater Wolfwere
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset704320","ARW000",1)
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFVA01",[704.320],0)  // Vampiric Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFVA01",[704.320],0)  // Vampiric Wolf
    CreateCreature("WOLFVA01",[704.320],0)  // Vampiric Wolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #1
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    CreateCreature("WEREWO",[704.320],0)  // Werewolf
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFGR01",[704.320],0)  // Greater Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("ROGTRO",[704.320],0)  // Sea Troll
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFVA01",[704.320],0)  // Vampiric Wolf
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("WOLFVA01",[704.320],0)  // Vampiric Wolf
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    CreateCreature("WOLFWE",[704.320],0)  // Wolfwere
    SetGlobalTimer("2000704320","ARW000",EIGHT_HOURS)
END


IF
  !Range([PC],35)
  Global("SpawnReset704320","ARW000",1)
  GlobalTimerExpired("2000704320","ARW000")
THEN
  RESPONSE #100
    SetGlobal("SpawnReset704320","ARW000",0)
    SetGlobal("RandomBeenSet704320","ARW000",0)
    SetGlobal("RandomSet704320_1","ARW000",0)
END

IF
  Range([PC],35)
  Global("SpawnReset704320","ARW000",0)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset704320","ARW000",1)
    CreateCreature("BEARBR",[704.320],0)  // ~Brown Bear~
    SetGlobalTimer("2000704320","ARW000",2400)
END

