IF
  RandomNum(1,1)
  Global("RandomSet30961204_0","AR6519",0)
  Global("RandomBeenSet30961204","AR6519",0)
THEN
  RESPONSE #100
    SetGlobal("RandomSet30961204_0","AR6519",1)
    SetGlobal("RandomBeenSet30961204","AR6519",1)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #45
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #35
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELDIS",[3096.1204],0)  // Skeleton Dispel
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)

END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    CreateCreature("SKELDIS",[3096.1204],0)  // Skeleton Dispel
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    CreateCreature("SKELDIS",[3096.1204],0)  // Skeleton Dispel
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    CreateCreature("SKELDIS",[3096.1204],0)  // Skeleton Dispel
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    CreateCreature("SKELDIS",[3096.1204],0)  // Skeleton Dispel
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    CreateCreature("SKELDIS",[3096.1204],0)  // Skeleton Dispel
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    CreateCreature("SKELDIS",[3096.1204],0)  // Skeleton Dispel
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    CreateCreature("SKELDIS",[3096.1204],0)  // Skeleton Dispel
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    CreateCreature("SKELDIS",[3096.1204],0)  // Skeleton Dispel
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #45
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #35
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELET03",[3096.1204],0)  // Skeleton
    CreateCreature("SKELET02",[3096.1204],0)  // Skeleton (Archer)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELDIS",[3096.1204],0)  // Skeleton Dispel
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)

END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    CreateCreature("SKELDIS",[3096.1204],0)  // Skeleton Dispel
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    CreateCreature("SKELDIS",[3096.1204],0)  // Skeleton Dispel
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset30961204","AR6519",0)
  Global("RandomSet30961204_0","AR6519",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset30961204","AR6519",1)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    CreateCreature("SKELDIS",[3096.1204],0)  // Skeleton Dispel
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    CreateCreature("SKELDIS",[3096.1204],0)  // Skeleton Dispel
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    CreateCreature("SKELDIS",[3096.1204],0)  // Skeleton Dispel
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    CreateCreature("SKELICE",[3096.1204],0)  // Skeleton Ice
    CreateCreature("SKELDIS",[3096.1204],0)  // Skeleton Dispel
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    CreateCreature("SKELFIRE",[3096.1204],0)  // Skeleton Fire
    CreateCreature("SKELDIS",[3096.1204],0)  // Skeleton Dispel
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA",[3096.1204],0)  // Skeleton Warrior
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELWA03",[3096.1204],0)  // Skeleton Warrior (Archer)
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    CreateCreature("SKELACI",[3096.1204],0)  // Skeleton Acid
    CreateCreature("SKELDIS",[3096.1204],0)  // Skeleton Dispel
    SetGlobalTimer("261930961204","AR6519",EIGHT_HOURS)
END

IF
  !Range([PC],35)
  Global("SpawnReset30961204","AR6519",1)
  GlobalTimerExpired("261930961204","AR6519")
THEN
  RESPONSE #100
    SetGlobal("SpawnReset30961204","AR6519",0)
    SetGlobal("RandomBeenSet30961204","AR6519",0)
    SetGlobal("RandomSet30961204_0","AR6519",0)
END

IF
  Range([PC],35)
  Global("SpawnReset30961204","AR6519",0)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset30961204","AR6519",1)
    CreateCreature("SKELET_C",[3096.1204],0)  // ~Skeleton~
    SetGlobalTimer("261930961204","AR6519",2400)
END

