IF
  RandomNum(1,1)
  Global("RandomSet3011323_0","AR6600",0)
  Global("RandomBeenSet3011323","AR6600",0)
THEN
  RESPONSE #100
    SetGlobal("RandomSet3011323_0","AR6600",1)
    SetGlobal("RandomBeenSet3011323","AR6600",1)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #45
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("COW",[3011.323],0) // Cow
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #25
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("COW",[3011.323],0) // Cow
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("COW",[3011.323],0) // Cow
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("COW",[3011.323],0) // Cow
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("COW",[3011.323],0) // Cow
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("COW",[3011.323],0) // Cow
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #35
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("COW",[3011.323],0) // Cow
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("COW",[3011.323],0) // Cow
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("COW",[3011.323],0) // Cow
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #8
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #25
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("COW",[3011.323],0) // Cow
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("COW",[3011.323],0) // Cow
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #4
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("COW",[3011.323],0) // Cow
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("COW",[3011.323],0) // Cow
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #35
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #7
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #8
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("COW",[3011.323],0) // Cow
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #7
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #8
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("COW",[3011.323],0) // Cow
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #12
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #13
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("COW",[3011.323],0) // Cow
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("COW",[3011.323],0) // Cow
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("COW",[3011.323],0) // Cow
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #12
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #13
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("COW",[3011.323],0) // Cow
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #12
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #13
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("COW",[3011.323],0) // Cow
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("COW",[3011.323],0) // Cow
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #8
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("COW",[3011.323],0) // Cow
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("COW",[3011.323],0) // Cow
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #12
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #13
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #11
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("COW",[3011.323],0) // Cow
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #25
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("COW",[3011.323],0) // Cow
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("COW",[3011.323],0) // Cow
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #12
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #13
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("COW",[3011.323],0) // Cow
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #12
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #13
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("COW",[3011.323],0) // Cow
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #12
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #13
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("COW",[3011.323],0) // Cow
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("COW",[3011.323],0) // Cow
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #12
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #13
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("COW",[3011.323],0) // Cow
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("COW",[3011.323],0) // Cow
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END


IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("COW",[3011.323],0) // Cow
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #12
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #13
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("COW",[3011.323],0) // Cow
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #12
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #13
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("COW",[3011.323],0) // Cow
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("COW",[3011.323],0) // Cow
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInPartyAlive(1)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #18
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #18
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #24
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInPartyAlive(2)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #11
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #8
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #8
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInPartyAlive(3)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInPartyAlive(4)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #7
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #31
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInPartyAlive(5)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInPartyAlive(6)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #7
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #13
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInPartyAlive(1)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #8
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #8
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #19
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInPartyAlive(2)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #13
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #13
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #24
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInPartyAlive(3)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #13
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #13
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #19
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInPartyAlive(4)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #7
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #13
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #13
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInPartyAlive(5)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #7
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #12
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #12
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #8
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInPartyAlive(6)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #8
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #8
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #8
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #8
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #8
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInPartyAlive(1)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #8
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #8
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #24
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInPartyAlive(2)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #13
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #13
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #13
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #13
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #13
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInPartyAlive(3)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #12
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #12
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInPartyAlive(4)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #8
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #8
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #8
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #21
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #13
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #13
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInPartyAlive(5)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #8
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #8
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #8
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #8
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #8
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInPartyAlive(6)  
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #16
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #11
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #12
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #12
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #12
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #12
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #7
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #11
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #11
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #11
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #13
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #13
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    CreateCreature("DOGWI",[3011.323],0) // Wild Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #8
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #8
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #11
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #12
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #12
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #8
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #8
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #8
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #11
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #8
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #8
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #13
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #13
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    CreateCreature("GIBBER2",[3011.323],0) // Diseased Gibberling
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #27
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #27
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #19
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #12
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #12
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #12
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    CreateCreature("DOGWA",[3011.323],0) // War Dog
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #14
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #28
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #28
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #24
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #23
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #23
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLFWE",[3011.323],0) // Wolfwere
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #12
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #12
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #12
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #14
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLFWE",[3011.323],0) // Wolfwere
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END


IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #7
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #12
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #12
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLFWE",[3011.323],0) // Wolfwere
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END


IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #12
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #12
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #12
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLFWE",[3011.323],0) // Wolfwere
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLFWE",[3011.323],0) // Wolfwere
    CreateCreature("WOLFWE",[3011.323],0) // Wolfwere
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #35
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #12
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #12
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLFWE",[3011.323],0) // Wolfwere
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLFWE",[3011.323],0) // Wolfwere
    CreateCreature("WOLFWE",[3011.323],0) // Wolfwere
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #8
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #8
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #8
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #8
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #8
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    CreateCreature("WOLF01",[3011.323],0) // Wolf
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #12
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #12
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #12
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    CreateCreature("BEARBL",[3011.323],0) // Black Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #24
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLFWE",[3011.323],0) // Wolfwere
    CreateCreature("WOLFWE",[3011.323],0) // Wolfwere
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #22
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #22
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #22
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #17
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLFWE",[3011.323],0) // Wolfwere
    CreateCreature("WOLFWE",[3011.323],0) // Wolfwere
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #17
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLFWE",[3011.323],0) // Wolfwere
    CreateCreature("WOLFWE",[3011.323],0) // Wolfwere
    CreateCreature("WOLFWE",[3011.323],0) // Wolfwere
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset3011323","AR6600",0)
  Global("RandomSet3011323_0","AR6600",1)
THEN
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    CreateCreature("BEARBR",[3011.323],0) // Brown Bear
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #16
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLFWE",[3011.323],0) // Wolfwere
    CreateCreature("WOLFWE",[3011.323],0) // Wolfwere
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #17
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLFWE",[3011.323],0) // Wolfwere
    CreateCreature("WOLFWE",[3011.323],0) // Wolfwere
    CreateCreature("WOLFWE",[3011.323],0) // Wolfwere
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
  RESPONSE #17
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("WOLFWE",[3011.323],0) // Wolfwere
    CreateCreature("WOLFWE",[3011.323],0) // Wolfwere
    CreateCreature("WOLFWE",[3011.323],0) // Wolfwere
    CreateCreature("WOLFWE",[3011.323],0) // Wolfwere
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END




IF
  !Range([PC],35)
  Global("SpawnReset3011323","AR6600",1)
  GlobalTimerExpired("27003011323","AR6600")
THEN
  RESPONSE #100
    SetGlobal("SpawnReset3011323","AR6600",0)
    SetGlobal("RandomBeenSet3011323","AR6600",0)
    SetGlobal("RandomSet3011323_0","AR6600",0)
END

IF
  Range([PC],35)
  Global("SpawnReset3011323","AR6600",0)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset3011323","AR6600",1)
    CreateCreature("GIBBER2",[3011.323],0)  // ~Diseased Gibberling~
    SetGlobalTimer("27003011323","AR6600",EIGHT_HOURS)
END

