IF
  Global("RandomBeenSet437763","%XvartVillage%",0)
THEN
  RESPONSE %spawnRem%
    SetGlobal("RandomBeenSet437763","%XvartVillage%",1)
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
RESPONSE %spawnPerc%
    Continue()
END
//Spawnpoint % code above

IF
  RandomNum(1,1)
  Global("RandomSet437763_3","%XvartVillage%",0)
  Global("RandomBeenSet437763","%XvartVillage%",0)
THEN
  RESPONSE #100
    SetGlobal("RandomSet437763_3","%XvartVillage%",1)
    SetGlobal("RandomBeenSet437763","%XvartVillage%",1)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #8
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #18
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #8
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #25
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #8
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #8
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #18
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #8
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #8
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #15
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #4
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #15
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #6
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #4
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #6
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #4
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #4
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #4
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #4
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #4
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #4
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #4
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #4
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #4
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #4
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #4
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #4
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #4
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("BEARGR",[437.763],0)  // Grizzly Bear
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("BEARGR",[437.763],0)  // Grizzly Bear
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("BEARGR",[437.763],0)  // Grizzly Bear
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #4
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("BEARGR",[437.763],0)  // Grizzly Bear
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("BEARGR",[437.763],0)  // Grizzly Bear
    CreateCreature("BEARGR",[437.763],0)  // Grizzly Bear
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("BEARGR",[437.763],0)  // Grizzly Bear
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("BEARGR",[437.763],0)  // Grizzly Bear
    CreateCreature("BEARGR",[437.763],0)  // Grizzly Bear
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("BEARGR",[437.763],0)  // Grizzly Bear
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("BEARGR",[437.763],0)  // Grizzly Bear
    CreateCreature("BEARGR",[437.763],0)  // Grizzly Bear
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #4
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END


IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #8
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #18
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #8
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #25
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #8
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #8
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #18
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #8
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #8
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #15
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #4
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #15
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #6
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #4
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #6
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #4
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #4
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #4
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #4
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #7
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #4
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #4
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #4
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #4
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #4
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #4
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #4
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #4
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #4
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("BEARGR",[437.763],0)  // Grizzly Bear
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("BEARGR",[437.763],0)  // Grizzly Bear
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("BEARGR",[437.763],0)  // Grizzly Bear
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #4
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("BEARGR",[437.763],0)  // Grizzly Bear
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("BEARGR",[437.763],0)  // Grizzly Bear
    CreateCreature("BEARGR",[437.763],0)  // Grizzly Bear
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("BEARGR",[437.763],0)  // Grizzly Bear
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("BEARGR",[437.763],0)  // Grizzly Bear
    CreateCreature("BEARGR",[437.763],0)  // Grizzly Bear
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset437763","%XvartVillage%",0)
  Global("RandomSet437763_3","%XvartVillage%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    CreateCreature("XVART",[437.763],0)  // Xvart
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #40
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #2
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WOLF01",[437.763],0)  // Wolf
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    CreateCreature("WORG",[437.763],0)  // Worg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("BEARGR",[437.763],0)  // Grizzly Bear
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("BEARGR",[437.763],0)  // Grizzly Bear
    CreateCreature("BEARGR",[437.763],0)  // Grizzly Bear
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #4
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
  RESPONSE #3
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    CreateCreature("ANKHEG",[437.763],0)  // Ankheg
    SetGlobalTimer("4700437763","%XvartVillage%",EIGHT_HOURS)
END

IF
  !Range([PC],35)
  Global("SpawnReset437763","%XvartVillage%",1)
  GlobalTimerExpired("4700437763","%XvartVillage%")
THEN
  RESPONSE #100
    SetGlobal("SpawnReset437763","%XvartVillage%",0)
    SetGlobal("RandomBeenSet437763","%XvartVillage%",0)
    SetGlobal("RandomSet437763_3","%XvartVillage%",0)
END

IF
  Range([PC],35)
  Global("SpawnReset437763","%XvartVillage%",0)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset437763","%XvartVillage%",1)
    CreateCreature("XVART",[437.763],0)  // ~Xvart~
    SetGlobalTimer("4700437763","%XvartVillage%",2400)
END

